/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as SearchRouteImport } from './routes/search'
import { Route as QuizzesRouteImport } from './routes/quizzes'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TimetableLecturesRouteImport } from './routes/timetable.lectures'
import { Route as TimetableExamsRouteImport } from './routes/timetable.exams'
import { Route as QuizzesIdRouteImport } from './routes/quizzes.$id'
import { Route as DepartmentsSlugRouteImport } from './routes/departments.$slug'
import { Route as CoursesCodeRouteImport } from './routes/courses.$code'
import { Route as AnnouncementsSlugRouteImport } from './routes/announcements.$slug'

const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesRoute = QuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableLecturesRoute = TimetableLecturesRouteImport.update({
  id: '/lectures',
  path: '/lectures',
  getParentRoute: () => TimetableRoute,
} as any)
const TimetableExamsRoute = TimetableExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => TimetableRoute,
} as any)
const QuizzesIdRoute = QuizzesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => QuizzesRoute,
} as any)
const DepartmentsSlugRoute = DepartmentsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DepartmentsRoute,
} as any)
const CoursesCodeRoute = CoursesCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => CoursesRoute,
} as any)
const AnnouncementsSlugRoute = AnnouncementsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AnnouncementsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/announcements': typeof AnnouncementsRouteWithChildren
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/departments': typeof DepartmentsRouteWithChildren
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/quizzes': typeof QuizzesRouteWithChildren
  '/search': typeof SearchRoute
  '/timetable': typeof TimetableRouteWithChildren
  '/announcements/$slug': typeof AnnouncementsSlugRoute
  '/courses/$code': typeof CoursesCodeRoute
  '/departments/$slug': typeof DepartmentsSlugRoute
  '/quizzes/$id': typeof QuizzesIdRoute
  '/timetable/exams': typeof TimetableExamsRoute
  '/timetable/lectures': typeof TimetableLecturesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/announcements': typeof AnnouncementsRouteWithChildren
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/departments': typeof DepartmentsRouteWithChildren
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/quizzes': typeof QuizzesRouteWithChildren
  '/search': typeof SearchRoute
  '/timetable': typeof TimetableRouteWithChildren
  '/announcements/$slug': typeof AnnouncementsSlugRoute
  '/courses/$code': typeof CoursesCodeRoute
  '/departments/$slug': typeof DepartmentsSlugRoute
  '/quizzes/$id': typeof QuizzesIdRoute
  '/timetable/exams': typeof TimetableExamsRoute
  '/timetable/lectures': typeof TimetableLecturesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/announcements': typeof AnnouncementsRouteWithChildren
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/departments': typeof DepartmentsRouteWithChildren
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/quizzes': typeof QuizzesRouteWithChildren
  '/search': typeof SearchRoute
  '/timetable': typeof TimetableRouteWithChildren
  '/announcements/$slug': typeof AnnouncementsSlugRoute
  '/courses/$code': typeof CoursesCodeRoute
  '/departments/$slug': typeof DepartmentsSlugRoute
  '/quizzes/$id': typeof QuizzesIdRoute
  '/timetable/exams': typeof TimetableExamsRoute
  '/timetable/lectures': typeof TimetableLecturesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/announcements'
    | '/auth'
    | '/calendar'
    | '/contact'
    | '/courses'
    | '/departments'
    | '/events'
    | '/gallery'
    | '/quizzes'
    | '/search'
    | '/timetable'
    | '/announcements/$slug'
    | '/courses/$code'
    | '/departments/$slug'
    | '/quizzes/$id'
    | '/timetable/exams'
    | '/timetable/lectures'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/announcements'
    | '/auth'
    | '/calendar'
    | '/contact'
    | '/courses'
    | '/departments'
    | '/events'
    | '/gallery'
    | '/quizzes'
    | '/search'
    | '/timetable'
    | '/announcements/$slug'
    | '/courses/$code'
    | '/departments/$slug'
    | '/quizzes/$id'
    | '/timetable/exams'
    | '/timetable/lectures'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/announcements'
    | '/auth'
    | '/calendar'
    | '/contact'
    | '/courses'
    | '/departments'
    | '/events'
    | '/gallery'
    | '/quizzes'
    | '/search'
    | '/timetable'
    | '/announcements/$slug'
    | '/courses/$code'
    | '/departments/$slug'
    | '/quizzes/$id'
    | '/timetable/exams'
    | '/timetable/lectures'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnnouncementsRoute: typeof AnnouncementsRouteWithChildren
  AuthRoute: typeof AuthRoute
  CalendarRoute: typeof CalendarRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  DepartmentsRoute: typeof DepartmentsRouteWithChildren
  EventsRoute: typeof EventsRoute
  GalleryRoute: typeof GalleryRoute
  QuizzesRoute: typeof QuizzesRouteWithChildren
  SearchRoute: typeof SearchRoute
  TimetableRoute: typeof TimetableRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes': {
      id: '/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof QuizzesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable/lectures': {
      id: '/timetable/lectures'
      path: '/lectures'
      fullPath: '/timetable/lectures'
      preLoaderRoute: typeof TimetableLecturesRouteImport
      parentRoute: typeof TimetableRoute
    }
    '/timetable/exams': {
      id: '/timetable/exams'
      path: '/exams'
      fullPath: '/timetable/exams'
      preLoaderRoute: typeof TimetableExamsRouteImport
      parentRoute: typeof TimetableRoute
    }
    '/quizzes/$id': {
      id: '/quizzes/$id'
      path: '/$id'
      fullPath: '/quizzes/$id'
      preLoaderRoute: typeof QuizzesIdRouteImport
      parentRoute: typeof QuizzesRoute
    }
    '/departments/$slug': {
      id: '/departments/$slug'
      path: '/$slug'
      fullPath: '/departments/$slug'
      preLoaderRoute: typeof DepartmentsSlugRouteImport
      parentRoute: typeof DepartmentsRoute
    }
    '/courses/$code': {
      id: '/courses/$code'
      path: '/$code'
      fullPath: '/courses/$code'
      preLoaderRoute: typeof CoursesCodeRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/announcements/$slug': {
      id: '/announcements/$slug'
      path: '/$slug'
      fullPath: '/announcements/$slug'
      preLoaderRoute: typeof AnnouncementsSlugRouteImport
      parentRoute: typeof AnnouncementsRoute
    }
  }
}

interface AnnouncementsRouteChildren {
  AnnouncementsSlugRoute: typeof AnnouncementsSlugRoute
}

const AnnouncementsRouteChildren: AnnouncementsRouteChildren = {
  AnnouncementsSlugRoute: AnnouncementsSlugRoute,
}

const AnnouncementsRouteWithChildren = AnnouncementsRoute._addFileChildren(
  AnnouncementsRouteChildren,
)

interface CoursesRouteChildren {
  CoursesCodeRoute: typeof CoursesCodeRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesCodeRoute: CoursesCodeRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface DepartmentsRouteChildren {
  DepartmentsSlugRoute: typeof DepartmentsSlugRoute
}

const DepartmentsRouteChildren: DepartmentsRouteChildren = {
  DepartmentsSlugRoute: DepartmentsSlugRoute,
}

const DepartmentsRouteWithChildren = DepartmentsRoute._addFileChildren(
  DepartmentsRouteChildren,
)

interface QuizzesRouteChildren {
  QuizzesIdRoute: typeof QuizzesIdRoute
}

const QuizzesRouteChildren: QuizzesRouteChildren = {
  QuizzesIdRoute: QuizzesIdRoute,
}

const QuizzesRouteWithChildren =
  QuizzesRoute._addFileChildren(QuizzesRouteChildren)

interface TimetableRouteChildren {
  TimetableExamsRoute: typeof TimetableExamsRoute
  TimetableLecturesRoute: typeof TimetableLecturesRoute
}

const TimetableRouteChildren: TimetableRouteChildren = {
  TimetableExamsRoute: TimetableExamsRoute,
  TimetableLecturesRoute: TimetableLecturesRoute,
}

const TimetableRouteWithChildren = TimetableRoute._addFileChildren(
  TimetableRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnnouncementsRoute: AnnouncementsRouteWithChildren,
  AuthRoute: AuthRoute,
  CalendarRoute: CalendarRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRouteWithChildren,
  DepartmentsRoute: DepartmentsRouteWithChildren,
  EventsRoute: EventsRoute,
  GalleryRoute: GalleryRoute,
  QuizzesRoute: QuizzesRouteWithChildren,
  SearchRoute: SearchRoute,
  TimetableRoute: TimetableRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
